baseURL = "https://samikarkar.github.io"
disableLanguages = []
disqusShortname = ""
paginate = "4"
summaryLength = "30"
theme = "airspace-hugo"
title = "Sami Karkar | R&D Expertise in Acoustics & Vibrations"
[Languages.fr]
contentDir = "content/french"
copyright = "Copyright &copy; 2019 [Themefisher](https://themefisher.com) All Rights Reserved"
home = "Accueil"
languageCode = "fr-fr"
languageName = "FR"
weight = "1"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2019 [Themefisher](https://themefisher.com) All Rights Reserved"
home = "Home"
languageCode = "en-us"
languageName = "EN"
weight = "2"
[params]
author = "Sami Karkar"
contact_form_action = ""
description = ""
email = "sami.karkar@free.fr"
google_analitycs_id = ""
location = "Paris 17e"
logo = "images/logo.png"
multi_author = false
[params.nav_button]
enable = false
label = "Demander un devis"
link = "contact"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = ""
[params.search]
enable = true
[[params.social]]
icon = "ion-social-linkedin-outline"
link = "https://www.linkedin.com/in/sami-karkar-37414080/"
