baseURL = "file:///home/skarkar/samikarkar.github.io"
defaultContentLanguage = "fr"
disableLanguages = []
disqusShortname = ""
paginate = "4"
sectionPagesMenu = "main"
summaryLength = "30"
theme = "airspace-hugo-sami"
title = "Sami Karkar | R&D Expertise in Acoustics & Vibrations"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 Sami Karkar based on [Themefisher]"
home = "Home"
languageCode = "en-us"
languageName = "en"
weight = "2"
[Languages.fr]
contentDir = "content/french"
copyright = "Copyright &copy; 2020 Sami Karkar basé sur [Themefisher]"
home = "Accueil"
languageCode = "fr-fr"
languageName = "fr"
weight = "1"
[params]
author = "Sami Karkar"
contact_form_action = ""
description = ""
email = "sami.karkar@free.fr"
google_analitycs_id = ""
location = "Paris 17e"
logo = "images/My SK Logo 3 64pt.png"
multi_author = false
#[params.nav_button]
#enable = false
#label = "Demander un devis"
#link = "contact"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = ""
[params.search]
enable = true
[[params.social]]
icon = "ion-social-linkedin-outline"
link = "https://www.linkedin.com/in/sami-karkar-37414080/"
